// All JC Bali Property listings (one-time import) + i18n dictionary

export const LAND_LISTINGS = [
  { id: 'l1', name: 'Riverside Land — Petulu Ubud', loc: 'Ubud', sqm: 900, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2026/05/ubud-9r-1.jpg', href: 'https://jcbaliproperty.com/property/riverside-land-for-lease-in-petulu-ubud/' },
  { id: 'l2', name: 'Strategic Land Kerambitan', loc: 'Tabanan', sqm: 6500, tag: 'Sale', img: 'https://jcbaliproperty.com/wp-content/uploads/2026/03/65are2.jpg', href: 'https://jcbaliproperty.com/property/strategic-land-for-sale-in-kerambitan-great-investment-opportunity/' },
  { id: 'l3', name: 'Prime 36 Are — Jimbaran', loc: 'Jimbaran', sqm: 3600, tag: 'Freehold · Sale', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/10/freehold-36R-850x570.jpg', href: 'https://jcbaliproperty.com/property/prime-36-are-land-for-sale-in-jimbaran-close-to-the-beach/' },
  { id: 'l4', name: 'Prime Investment Land', loc: 'Babakan', sqm: 500, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/10/Untitled-design-14-850x570.jpg', href: 'https://jcbaliproperty.com/property/prime-investment-land-in-babakan-high-value-location-near-the-beach/' },
  { id: 'l5', name: '7 Are Riverside Land', loc: 'Buwit', sqm: 700, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/09/7-Are-1-850x570.jpg', href: 'https://jcbaliproperty.com/property/7-are-riverside-land-in-buwit-peaceful-green-surroundings/' },
  { id: 'l6', name: '4 Are Rice Field View', loc: 'Buduk', sqm: 400, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/09/Untitled-design-9-850x570.jpg', href: 'https://jcbaliproperty.com/property/4-are-rice-field-view-land-for-lease-in-buduk/' },
  { id: 'l7', name: 'Expansive 34 Are', loc: 'Kaba-Kaba', sqm: 3400, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/09/Untitled-design-7-850x570.jpg', href: 'https://jcbaliproperty.com/property/expansive-34-are-land-in-kaba-kaba-surrounded-by-rice-fields/' },
  { id: 'l8', name: 'Peaceful 8 Are Rice Field', loc: 'Nyambu', sqm: 800, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/09/Untitled-design-4-850x570.jpg', href: 'https://jcbaliproperty.com/property/peaceful-8-are-rice-field-land-in-nyambu/' },
  { id: 'l9', name: 'Cemagi Coastal Pink Zone', loc: 'Cemagi', sqm: 800, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/09/Untitled-design-3-850x570.jpg', href: 'https://jcbaliproperty.com/property/balis-hidden-jewel-8-are-land-in-cemagi-coastal-pink-zone/' },
  { id: 'l10', name: 'Golden 8.5 Are Ricefield', loc: 'Canggu', sqm: 850, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/09/Untitled-design-5-1140x764.jpg', href: 'https://jcbaliproperty.com/property/golden-investment-8-5-are-ricefield-land-in-canggu/' },
  { id: 'l11', name: 'Scenic 10 Are Rice Field', loc: 'Kaba-Kaba', sqm: 1000, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/09/Untitled-design-2-850x570.jpg', href: 'https://jcbaliproperty.com/property/scenic-10-are-rice-field-view-land-in-kaba-kaba/' },
  { id: 'l12', name: 'Hidden Sanctuary 14 Are', loc: 'Abianbase', sqm: 1400, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/09/1-5-850x570.jpg', href: 'https://jcbaliproperty.com/property/hidden-sanctuary-14-are-in-abianbase-surrounded-by-green/' },
  { id: 'l13', name: 'Leasehold Land Babakan', loc: 'Canggu', sqm: 200, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/09/1-3-1-850x570.jpg', href: 'https://jcbaliproperty.com/property/leasehold-land-in-babakan-canggu-bali-indonesia-size-2-are-200m2/' },
  { id: 'l14', name: 'Tranquil Riverside 12 Are', loc: 'Buwit', sqm: 1200, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/09/12-Are-Buwit-1-850x570.jpg', href: 'https://jcbaliproperty.com/property/tranquil-riverside-retreat-12-are-in-buwit/' },
  { id: 'l15', name: 'Leasehold 9 Are Ubud', loc: 'Ubud', sqm: 900, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/09/9-Are-Ubud-6-850x570.jpg', href: 'https://jcbaliproperty.com/property/leasehold-land-in-ubud-bali-indonesia-size-9-are-900m2/' },
  { id: 'l16', name: '10 Are Prime — Walk to Beach', loc: 'Cemagi', sqm: 1000, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/09/10-are-cemagi-2-850x570.jpg', href: 'https://jcbaliproperty.com/property/10-are-prime-land-in-cemagi-walking-distance-to-the-beach/' },
  { id: 'l17', name: '20 Are Rice Field View', loc: 'Ubud', sqm: 2000, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/09/Untitled-design-1-850x570.jpg', href: 'https://jcbaliproperty.com/property/ubud-opportunity-20-are-land-with-stunning-rice-field-view/' },
  { id: 'l18', name: 'Spacious 25 Are', loc: 'Ubud', sqm: 2500, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/09/20-R-2-UBUD-850x570.jpg', href: 'https://jcbaliproperty.com/property/spacious-25-are-land-in-ubud-perfect-for-villas-or-retreat/' },
  { id: 'l19', name: 'Rare 24 Are Green View', loc: 'Ubud', sqm: 2400, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/09/01-850x570.jpg', href: 'https://jcbaliproperty.com/property/rare-find-in-ubud-24-are-land-with-breathtaking-green-views/' },
  { id: 'l20', name: 'Endless 24.5 Are', loc: 'Ubud', sqm: 2450, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/09/ubud-850x570.jpg', href: 'https://jcbaliproperty.com/property/endless-possibilities-on-24-5-are-prime-ubud-land/' },
  { id: 'l21', name: '6.6 Are — Great Investment', loc: 'Tumbak Bayuh', sqm: 660, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/09/6R-1-850x570.jpg', href: 'https://jcbaliproperty.com/property/6-6-are-land-for-lease-in-tumbak-bayuh-bali-great-investment-opportunity/' },
  { id: 'l22', name: 'Spacious 32 Are — Ocean Breeze', loc: 'Cemagi', sqm: 1700, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/09/2-17r-cemagi-1140x764.jpg', href: 'https://jcbaliproperty.com/property/spacious-32-are-land-with-ocean-breeze-in-cemagi/' },
  { id: 'l23', name: 'Rare 4 Are Leasehold', loc: 'Cemagi', sqm: 400, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/09/4r-1-850x570.jpg', href: 'https://jcbaliproperty.com/property/rare-opportunity-4-are-leasehold-land-in-cemagi-bali/' },
  { id: 'l24', name: 'Long Leasehold 5/10 Are', loc: 'Babakan Tuka', sqm: 1000, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2024/05/Untitled-design-10-850x570.jpg', href: 'https://jcbaliproperty.com/property/long-leasehold-5-or-10-are-babakan-tuka-canggu/' },
  { id: 'l25', name: 'Leasehold 9 Are', loc: 'Pererenan', sqm: 940, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2023/08/WhatsApp-Image-2023-08-24-at-14.42.34-850x570.jpeg', href: 'https://jcbaliproperty.com/property/leasehold-land-in-pererenan-bali-indonesia-size-9-are-900m2/' },
]

export const VILLA_LISTINGS = [
  { id: 'v1', name: 'Exquisite 3BR Seaside Sanctuary', loc: 'Saba Beach', beds: 3, baths: 3, sqm: 2335, tag: 'For Sale', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/07/photo_6320860484730995258_y-768x570.jpg', href: 'https://jcbaliproperty.com/property/exquisite-3br-seaside-sanctuary-in-saba-beach-bali/' },
  { id: 'v2', name: 'Monochromatic Retreat 2BR', loc: 'Ubud', beds: 2, baths: 2, sqm: 168, tag: 'For Sale', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/12/19-6-1140x764.jpg', href: 'https://jcbaliproperty.com/property/monochromatic-design-retreat-2br-villa-in-ubud/' },
  { id: 'v3', name: 'Luxury 3BR with Private Pool', loc: 'Canggu', beds: 3, baths: 3, sqm: 500, tag: 'For Sale', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/07/6-3-850x570.jpg', href: 'https://jcbaliproperty.com/property/luxury-3-bedroom-villa-with-private-pool-canggu/' },
  { id: 'v4', name: 'Signature Private Estate 6BR', loc: 'Babakan', beds: 6, baths: 7, sqm: 1750, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2026/03/12-2-1140x764.jpg', href: 'https://jcbaliproperty.com/property/signature-luxury-private-estate-6br-villa-in-babakan/' },
  { id: 'v5', name: 'Stylish 5BR with Views', loc: 'Cemagi', beds: 5, baths: 5, sqm: 1000, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/07/WhatsApp-Image-2025-06-25-at-14.54.491-850x570.jpeg', href: 'https://jcbaliproperty.com/property/stylish-5br-villa-with-views-in-cemagi/' },
  { id: 'v6', name: 'Rice Field Sanctuary 2BR', loc: 'Cemagi', beds: 2, baths: 3, sqm: 140, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2026/02/16-1-1140x764.jpg', href: 'https://jcbaliproperty.com/property/rice-field-sanctuary-modern-2br-villa-in-cemagi/' },
  { id: 'v7', name: '2BR Hilltop Haven', loc: 'Ungasan', beds: 2, baths: 2, sqm: 130, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/12/11-2-scaled-1-1140x764.jpg', href: 'https://jcbaliproperty.com/property/2br-hilltop-haven-in-ungasan/' },
  { id: 'v8', name: 'Authentic Tropical 2BR', loc: 'Jimbaran', beds: 2, baths: 2, sqm: 135, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2026/01/8-5-1140x764.jpg', href: 'https://jcbaliproperty.com/property/authentic-tropical-2br-villa-in-jimbaran/' },
  { id: 'v9', name: 'Stonewall Paradise 4BR', loc: 'Kerobokan', beds: 4, baths: 4, sqm: 175, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2026/05/5-1-960x764.jpg', href: 'https://jcbaliproperty.com/property/stonewall-paradise-4br-villa-in-kerobokan-with-tropical-charm/' },
  { id: 'v10', name: 'Elegant Dreamy 2BR + Pool', loc: 'Canggu', beds: 2, baths: 3, sqm: 210, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2026/04/10-3-1140x764.jpg', href: 'https://jcbaliproperty.com/property/elegant-dreamy-2br-villa-with-private-pool-in-canggu-bali/' },
  { id: 'v11', name: '2BR with Huge Garden', loc: 'Berawa', beds: 2, baths: 3, sqm: 360, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2026/04/3-2-1140x764.jpg', href: 'https://jcbaliproperty.com/property/bali-living-goals-2br-villa-with-huge-garden-in-berawa/' },
  { id: 'v12', name: 'Modern Earth-Tone 2BR', loc: 'Buduk', beds: 2, baths: 2, sqm: 135, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2026/04/9-3-1140x764.jpg', href: 'https://jcbaliproperty.com/property/modern-earth-tone-2br-villa-in-buduk/' },
  { id: 'v13', name: 'Coastal Living 2BR', loc: 'Canggu', beds: 2, baths: 2, sqm: 135, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2026/04/1-1-1140x764.jpg', href: 'https://jcbaliproperty.com/property/coastal-living-2-br-villa-in-canggu/' },
  { id: 'v14', name: 'Fresh Tropical 2BR + Pool', loc: 'Tumbak Bayuh', beds: 2, baths: 3, sqm: 200, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2026/04/3-1140x764.jpg', href: 'https://jcbaliproperty.com/property/fresh-tropical-2br-villa-with-pool-in-tumbak-bayuh-ready-to-customize/' },
  { id: 'v15', name: 'Tropical Glow 3BR Sanctuary', loc: 'Munggu', beds: 3, baths: 3, sqm: 200, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2026/03/8-4-1140x764.jpg', href: 'https://jcbaliproperty.com/property/tropical-glow-sanctuary-3-br-villa-in-munggu-warm-bright-escape/' },
  { id: 'v16', name: 'Sunny Tropical 3BR', loc: 'Tumbak Bayuh', beds: 3, baths: 4, sqm: 200, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2026/03/16-1-1140x764.jpg', href: 'https://jcbaliproperty.com/property/sunny-tropical-paradise-elegant-hideaway-3br-villa-tumbak-bayuh/' },
  { id: 'v17', name: 'Bamboo Emerald Retreat 1BR', loc: 'Keliki', beds: 1, baths: 1, sqm: 350, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2026/03/10-1-1140x764.jpg', href: 'https://jcbaliproperty.com/property/bamboo-emerald-retreat-1br-villa-in-keliki/' },
  { id: 'v18', name: '1BR Warm Wooden Touch', loc: 'Jimbaran', beds: 1, baths: 1, sqm: 170, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2026/02/19-1-1140x764.jpg', href: 'https://jcbaliproperty.com/property/1br-villa-with-warm-wooden-touch-in-jimbaran/' },
  { id: 'v19', name: '1BR Essence Tropical', loc: 'Uluwatu', beds: 1, baths: 1, sqm: 125, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2026/02/1-1-1140x764.jpg', href: 'https://jcbaliproperty.com/property/1br-essence-tropical-villa-in-uluwatu/' },
  { id: 'v20', name: 'Wave Garden 2BR — Near Beach', loc: 'Cemagi', beds: 2, baths: 2, sqm: 160, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2026/01/3.png', href: 'https://jcbaliproperty.com/property/wave-garden-tranquil-2br-villa-near-the-beach-in-cemagi/' },
  { id: 'v21', name: 'Refined 3BR Retreat', loc: 'Balangan', beds: 3, baths: 4, sqm: 150, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2026/01/8-10-1140x764.jpg', href: 'https://jcbaliproperty.com/property/refined-3br-villa-retreat-in-balangan/' },
  { id: 'v22', name: 'Green Escape 2BR + Pool', loc: 'Kaba-Kaba', beds: 2, baths: 2, sqm: 200, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2026/01/17-2-1140x764.jpg', href: 'https://jcbaliproperty.com/property/green-escape-2br-villa-with-private-pool-in-kaba-kaba/' },
  { id: 'v23', name: 'White, Bright & Serene 4BR', loc: 'Jimbaran', beds: 4, baths: 4, sqm: 500, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/12/1-17-1140x764.jpg', href: 'https://jcbaliproperty.com/property/white-bright-and-serene-4br-villa-in-jimbaran/' },
  { id: 'v24', name: 'Sunlit Mediterranean Home 3BR', loc: 'Padonan', beds: 3, baths: 3, sqm: 141, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/12/9-19.png', href: 'https://jcbaliproperty.com/property/sunlit-mediterranean-home-in-the-heart-of-padonan/' },
  { id: 'v25', name: 'Hidden Gem — Rice Field View', loc: 'Tanah Lot', beds: 2, baths: 2, sqm: 150, tag: 'Lease', img: 'https://jcbaliproperty.com/wp-content/uploads/2025/09/13-4-850x570.jpg', href: 'https://jcbaliproperty.com/property/hidden-gem-villa-with-rice-field-view-tanah-lot-escape/' },
]

export const TESTIMONIALS = [
  { quote: 'Theo guided us through every step — title verification, notary, even introductions to a local builder. With Jaya Carita we felt informed, never pressured. Two years on, our Cemagi villa is fully booked year-round.', name: 'Marc & Camille D.', role: 'Investors, Paris' },
  { quote: 'I had spoken to five agencies before Jaya Carita Bali. Theo was the only one who said "this parcel is not right for you" — and showed me three better ones the same day. That honesty closed the deal.', name: 'Dmitry K.', role: 'Founder, Moscow' },
  { quote: 'As foreign buyers we were nervous about ownership structures in Indonesia. Theo and the JC Bali team handled the PT PMA setup end-to-end. Transparent, professional, and genuinely kind.', name: 'James & Priya R.', role: 'Family Office, Singapore' },
  { quote: 'The Ubud land we bought through Theo has appreciated 40% in eighteen months. But more importantly, the process was calm. He treats clients like long-term relationships, not transactions.', name: 'Sofia L.', role: 'Architect, Lisbon' },
]

// i18n dictionary — EN / ID / RU
export const TRANSLATIONS = {
  en: {
    nav_collection: 'Collection',
    nav_villas: 'Villas',
    nav_lands: 'Lands',
    nav_lifestyle: 'Bali Life',
    nav_invest: 'Invest',
    nav_voices: 'Voices',
    nav_contact: 'Contact',
    nav_cta: 'Begin a Conversation',
    hero_eyebrow: 'Theo — Digital Marketing at Jaya Carita Bali Property',
    hero_title_1: 'Your Bali story,',
    hero_title_em: 'begins',
    hero_title_2: 'with land.',
    hero_sub: "I'm Theo. I help foreign investors, founders and lifestyle buyers discover the right land and villa opportunities in Bali — backed by the trusted portfolio of Jaya Carita Bali Property.",
    hero_cta: 'View the Collection',
    view_villas: 'Browse All Villas',
    view_lands: 'Browse All Land',
    wa_now: 'WhatsApp Theo Now',
    email_theo: 'Email Theo',
    back_home: '← Back home',
    villas_title: 'Villas of Bali',
    villas_sub: 'A complete portfolio of villa-for-sale and villa-for-lease opportunities, curated from Jaya Carita Bali Property.',
    lands_title: 'Land in Bali',
    lands_sub: 'Every active land parcel in our portfolio — from beachside Cemagi to riverside Ubud. Pre-vetted, legally clear.',
    total_properties: 'properties',
  },
  id: {
    nav_collection: 'Koleksi',
    nav_villas: 'Villa',
    nav_lands: 'Tanah',
    nav_lifestyle: 'Hidup di Bali',
    nav_invest: 'Investasi',
    nav_voices: 'Testimoni',
    nav_contact: 'Kontak',
    nav_cta: 'Mulai Percakapan',
    hero_eyebrow: 'Theo — Digital Marketing di Jaya Carita Bali Property',
    hero_title_1: 'Cerita Bali Anda,',
    hero_title_em: 'dimulai',
    hero_title_2: 'dari tanah.',
    hero_sub: 'Saya Theo. Saya membantu investor asing, pengusaha, dan pembeli gaya hidup menemukan peluang tanah dan villa yang tepat di Bali — didukung portofolio terpercaya Jaya Carita Bali Property.',
    hero_cta: 'Lihat Koleksi',
    view_villas: 'Lihat Semua Villa',
    view_lands: 'Lihat Semua Tanah',
    wa_now: 'WhatsApp Theo Sekarang',
    email_theo: 'Email Theo',
    back_home: '← Kembali',
    villas_title: 'Villa di Bali',
    villas_sub: 'Portofolio lengkap villa untuk dijual dan disewakan dari Jaya Carita Bali Property.',
    lands_title: 'Tanah di Bali',
    lands_sub: 'Seluruh tanah aktif di portofolio kami — dari Cemagi tepi pantai hingga Ubud tepi sungai. Sudah diverifikasi legal.',
    total_properties: 'properti',
  },
  ru: {
    nav_collection: 'Коллекция',
    nav_villas: 'Виллы',
    nav_lands: 'Земля',
    nav_lifestyle: 'Жизнь на Бали',
    nav_invest: 'Инвестиции',
    nav_voices: 'Отзывы',
    nav_contact: 'Контакты',
    nav_cta: 'Начать разговор',
    hero_eyebrow: 'Тео — Цифровой маркетинг, Jaya Carita Bali Property',
    hero_title_1: 'Ваша история Бали,',
    hero_title_em: 'начинается',
    hero_title_2: 'с земли.',
    hero_sub: 'Я Тео. Помогаю иностранным инвесторам, основателям и покупателям недвижимости для жизни найти подходящие земельные участки и виллы на Бали — при поддержке проверенного портфолио Jaya Carita Bali Property.',
    hero_cta: 'Смотреть коллекцию',
    view_villas: 'Все виллы',
    view_lands: 'Вся земля',
    wa_now: 'WhatsApp Тео сейчас',
    email_theo: 'Email Тео',
    back_home: '← Назад',
    villas_title: 'Виллы Бали',
    villas_sub: 'Полный портфель вилл на продажу и в аренду от Jaya Carita Bali Property.',
    lands_title: 'Земля на Бали',
    lands_sub: 'Все доступные участки в нашем портфолио — от прибрежного Чемаги до речного Убуда. Юридически проверены.',
    total_properties: 'объектов',
  },
}

export const WHATSAPP = 'https://wa.me/6281918238875?text=Hi%20Theo%2C%20I%27m%20interested%20in%20exploring%20Bali%20property%20opportunities%20with%20Jaya%20Carita%20Bali.'
export const EMAIL = 'tsinjal52@gmail.com'
export const INSTAGRAM = 'https://instagram.com/Theo_JCPropertyagent'
export const PHONE_DISPLAY = '+62 819 1823 8875'
export const OFFICE_URL = 'https://maps.app.goo.gl/umG3aRvZ4qjTqKXq6'
export const OFFICE_ADDR = 'Jalan Betaka No 3a, Dalung, Kuta Utara, Badung, Bali 80361'
